# -*- coding: utf-8 -*-
"""cleans_up

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1I89uglNXoJyqHbd81EHtv-GY-K5Dt3uX
"""

from google.colab import drive
drive.mount('/content/drive')

!ls '/content/drive/MyDrive/'

import pandas as pd
df = pd.read_excel('/content/drive/MyDrive/temp_evol.xlsx')

df

df['Element'].unique()

df.describe()

df.isnull().sum()

df.sample(10)

df.head(10)

df(['Code'].unique)

df[df['Area'] == "France"]

df['Hydro Generation - TWh']

df_cleaned = df.drop(columns=['Area Code (FAO)','Element Code','Element','Unit','Flag','Flag Description'])

df_cleaned

df.isnull().sum()

df_cleaned_na = df_cleaned.dropna(how='any',axis=0)

df_cleaned_na.describe()

df_cleaned_na = df_cleaned_na.rename(columns={'Area': 'Country'})

df_cleaned_na

df_cleaned_na.to_excel('temp_evol.xlsx')